# Grantmaker settings
foundation_name: Ecoworks Foundation
tagline: Economic prosperity while replenishing the environment for future generations
email_public: info@ecoworksfoundation.org

# Social Media
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
twitter: 
facebook: 
instagram: 
github: 

# Site settings
title: Ecoworks Foundation | Venture Philanthropy for Sustainable Development
description: > # this means to start on the next line (which needs to be indendted two spaces)"
  Ecoworks Foundation is a 'venture philanthropy' foundation committed to enabling economic systems, products or services that promote economic growth while replenishing the environment for future generations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ecoworksfoundation.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - README.md
